# For VSCode REST Client extension
# @URL = http://localhost:5000


# @desc    Auth user & get token
# @route   POST /api/users/login
# @access  Public
POST {{URL}}/api/users/login1
Content-Type: application/json

{
    "email": "tester.one@personal.example.com",
    "password": "123"
}

###